#!/usr/bin/env bash

# last line of file needs to be empty
filename=./excludes_tomcat.txt
while read -r line; do
    excluded="$excluded -excludes $line"
done < "$filename"

if [ "$1" = "select" ]; then
  ./peass select -folder ../tomcat/ -startversion 6cf20b4a83f1e5b2ae86525b6b96389e801776b2 -endversion 073732c992f2120861015d1dc41d229e2abad904  \
  -testExecutor de.dagere.peass.execution.ant.AntTestExecutor -testTransformer de.dagere.peass.testtransformation.JUnitTestTransformer -classFolder java \
  -testClassFolder test $excluded
elif [ "$1" = "measure" ]; then
  ./peass measure -executionfile results/execute_tomcat.json -folder ../tomcat -vms 5 -iterations 40 -warmup 10 -repetitions 30 \
  -startversion 6cf20b4a83f1e5b2ae86525b6b96389e801776b2 -endversion 073732c992f2120861015d1dc41d229e2abad904  \
  -testExecutor de.dagere.peass.execution.ant.AntTestExecutor -testTransformer de.dagere.peass.testtransformation.JUnitTestTransformer -classFolder java \
  -testClassFolder test -timeout 20
  ./peass getchanges -data ../tomcat_peass/ -dependencyfile results/deps_tomcat.json
elif [ "$1" = "searchcause" ]; then
   ./peass searchcause -vms 5 -iterations 40 -warmup 10 -repetitions 30 -version 073732c992f2120861015d1dc41d229e2abad904  \
   -test org.apache.catalina.core.TestApplicationFilterConfig\#testBug54170 -folder ../tomcat -executionfile results/execute_tomcat.json \
   -testExecutor de.dagere.peass.execution.ant.AntTestExecutor -testTransformer de.dagere.peass.testtransformation.JUnitTestTransformer -classFolder java \
   -testClassFolder test -timeout 20
elif [ "$1" = "visualizerca" ]; then
  ./peass visualizerca -data ../tomcat_peass/ -propertyFolder results/properties_tomcat/
fi