#!/usr/bin/env bash

# last line of file needs to be empty
filename=./excludes_tomcat.txt
while read -r line; do
  if [[ ! -z "$line" && ! $line =~ ^#.* ]]; then
    excluded="$excluded -excludes $line"
  fi
done < "$filename"

if [ "$1" = "select" ]; then
  ./peass select -folder ../tomcat/ -classFolder java:webapps/examples/WEB-INF/classes:webapps/examples/jsp/plugin/applet -testClassFolder test \
  -testExecutor de.dagere.peass.execution.ant.AntTestExecutor -testTransformer de.dagere.peass.testtransformation.JUnitTestTransformer \
  -startversion 6cf20b4a83f1e5b2ae86525b6b96389e801776b2 -endversion b1ca09f34d0c22727bb5082053c7ae23c30ec8f2 -threads 1 -traceSizeInMb 10 -timeout 2 \
  -includes org.apache.* -excludes '*$*' $excluded
elif [ "$1" = "measure" ]; then
  ./peass measure -folder ../tomcat/ -classFolder -classFolder java:webapps/examples/WEB-INF/classes:webapps/examples/jsp/plugin/applet -testClassFolder test \
  -executionfile results/execute_tomcat.json \
  -testExecutor de.dagere.peass.execution.ant.AntTestExecutor -testTransformer de.dagere.peass.testtransformation.JUnitTestTransformer \
  -startversion 6cf20b4a83f1e5b2ae86525b6b96389e801776b2 -endversion b1ca09f34d0c22727bb5082053c7ae23c30ec8f2  \
  -vms 5 -iterations 40 -warmup 10 -repetitions 30 -measurementStrategy PARALLEL -timeout 5
  ./peass getchanges -data ../tomcat_peass/ -dependencyfile results/deps_tomcat.json
elif [ "$1" = "searchcause" ]; then
  ./peass searchcause -folder ../tomcat/ -classFolder -classFolder java:webapps/examples/WEB-INF/classes:webapps/examples/jsp/plugin/applet -testClassFolder test \
  -executionfile results/execute_tomcat.json \
  -testExecutor de.dagere.peass.execution.ant.AntTestExecutor -testTransformer de.dagere.peass.testtransformation.JUnitTestTransformer \
  -version b1ca09f34d0c22727bb5082053c7ae23c30ec8f2 -test org.apache.catalina.core.TestApplicationSessionCookieConfig\#testSetDomainInitPhase \
  -vms 5 -iterations 40 -warmup 10 -repetitions 30  -timeout 20 -traceSizeInMb 1000
elif [ "$1" = "visualizerca" ]; then
  ./peass visualizerca -data ../tomcat_peass/ -propertyFolder results/properties_tomcat/
fi